### ISSUE TITLE
zlist.pl for scripts.irssi.org

### ISSUE THREAD

**Issue by foonet** [irssi/scripts.irssi.org#103]
use strict;
use warnings;
use vars qw($VERSION %IRSSI);

$VERSION = '1.00';
%IRSSI = (
    authors => 'Ene Alin Gabriel',
    contact => 'zmeu@foonet.ro',
    name => 'zlist',
    description => 'Listing of channel names and save them',
    license => 'why?',
    url => 'http://foonet.ro',
);

use Irssi;

my %zlist = ();

sub collect {
    my ($server, $data) = @_;
    
    my (undef, $channel, $users, $topic) = split(/\s/, $data, 4);
    $topic = substr($topic, 1);
    
    $zlist{$channel} = [ $users, $topic ];
}

sub list {
    my ($data, $server) = @_;
    %zlist = ();
    
    print "%K[%n".$server->{'tag'}."%K]%n %B<-->%n zlist";
}

sub show {
    my ($server) = @_;
    my ($printstring, $channel);

    for $channel ( sort { ${ $zlist{$b} }[0] <=> ${ $zlist{$a} }[0] } keys %zlist ) {
	$printstring = "".$channel." :: ".sprintf("%d",${ $zlist{$channel} }[0])."\n";

	if (length ${ $zlist{$channel} }[1] > 0 ) {
	    $printstring .= "". ${ $zlist{$channel} }[1]."\n";
	}

	print $printstring;
        my $file="".$server->{'tag'}."_index.txt";
        open(my $fh, '>>', $file) or die ("can't open file: $1");
        print $fh "$printstring\n";
        close $fh;
    }
    
    %zlist = ();
    
    print "%K[%n".$server->{'tag'}."%K]%n %B<-->%n End of zlist";
}

Irssi::command_bind('list', \&list);
Irssi::signal_add('event 322', \&collect);
Irssi::signal_add('event 323', \&show);

print "%B<-->%n zlist v$VERSION: Simply use /list as you always do";

**Comment by dgl** [comment]
Sorry, you need to send this as a pull request, i.e. a git commit with the script changes in it (see `README.md` and github help). Also note: `license => 'why?',` isn't valid as an open source license.
