### ISSUE TITLE
Generate scripts.yaml from %IRSSI hash

### ISSUE THREAD

**Issue by dequis** [irssi/scripts.irssi.org#11]
The current scripts.yaml file is obviously autogenerated. It seems pointless to manually duplicate the effort of filling that information

I know perl parsing isn't trivial (and in fact I got this idea because i noticed the parsed information handles string concatenation wrong, which reminded me that the previous scripts repo worked this way), but any possible bugs in the parsing can be fixed with the magic of pull requests.

And submitting scripts is more effort than it should be.

**Comment by bw1** [comment]
here a few things for discussion 

new to old
https://gist.github.com/bw1/7a5efc80a1de82bac637/revisions

the generator script
https://github.com/bw1/scripts.irssi.org/commit/6cc2c93a2e9759358ddda5fffe83101584a47d98

small changes for the scripts
https://github.com/bw1/scripts.irssi.org/commit/1527beaea830b2ddef80e9a819d5cafa069a952c

**Comment by ailin-nemui** [comment]
@ahf I believe this is now implemented

**Comment by GeertHauwaerts** [comment]
So, can this be closed, or is there still work to be performed?
