### ISSUE TITLE
weather.pl

### ISSUE THREAD

**Issue by bw1** [irssi/scripts.irssi.org#110]
problem with the underling module Geo::Weather 

https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Weather

http://search.cpan.org/search?query=geo::weather&mode=all
->  27 Aug 2003

**Comment by bw1** [comment]
developer:

http://www.polarlava.com/blog/2004/03/17/the-polarlava-weather-project/

**Comment by incognico** [comment]
I suggest to contact the developer but it is probably better to remove non-functional scripts from the repo, especially if they rely on old and broken perl modules who have not seen updates for 12 years.

**Comment by bw1** [comment]
http://code.google.com/p/pikabot/source/browse/trunk/irssi/weather.pl?r=126
a newer script with the same name.
last revison 31. 12. 2011

needs this script a account?

$ weather.pl
Usage: weather.pl [partner ID] [key] [location]

https://profile.weather.com/#/registration/home-location

**Comment by bw1** [comment]
next:
	http://www.perl.lt/weather
	+ https://github.com/buzz/scripts/blob/master/weather.xslt
	+ "http://wxdata.weather.com/wxdata/weather/local/LHXX0002?cc=*&unit=m&dayf=2"
	+ /weather
	= 
	22:24 < bw1> Location: Kaunas, KU, LH:  Temperature: 2C  Conditions: Mostly Cloudy  Wind: 19km/h (12mph) (SW)  Tomorrow: -1C to 2C, AM Clouds / PM Sun

disadvantages:
* /usr/bin/xsltproc
* /usr/bin/curl
* weather.xslt

**Comment by bw1** [comment]
http://notes.benv.junerules.com/wp-content/uploads/2009/07/weather.pl

this script brings the weather from
http://weather.noaa.gov/
do the taskbar

no xslt, bin or moduls
:+1:

**Comment by incognico** [comment]
I can provide a weather script which uses data from yr.no when irssi/irssi#132 is fixed.

**Comment by ailin-nemui** [comment]
@incognico why cannot provide it just now? the issue is annoying but it can be fixed even without recompiling, just fixing the setting...

**Comment by GeertHauwaerts** [comment]
We welcome any updated version when it becomes available; unfortunately, we have decided to remove this version of the script until the deprecated and/or bugged module has been replaced.
