### ISSUE TITLE
trackbar uses deprecated perl functions

### ISSUE THREAD

**Issue by viq** [irssi/scripts.irssi.org#112]
trackbar.pl script in line 192 uses smartmatch (~~) which has been marked in newer perl as experimental, thus throwing errors and making scripts not load.

**Comment by bw1** [comment]
see pull request #114

**Comment by ailin-nemui** [comment]
I'd recommend avoiding this trackbar and using 1.4 -soliton or 2.2 which can be found elsewhere

**Comment by GeertHauwaerts** [comment]
Updated to v1.8, it was either this or removing the script; this seemed the better option.
