### ISSUE TITLE
script perl for restart irssi from irc 

### ISSUE THREAD

**Issue by bibidinu** [irssi/scripts.irssi.org#133]
hello guys 
would be useful to a script to remotely restart irssi
example admin nick on chan admin get !restart 
and is closed on the server and restart the process

tnx so much

**Comment by GeertHauwaerts** [comment]
You can use trigger.pl for that :)

**Comment by bibidinu** [comment]
perhaps I have not explained well 
what I intend to do is a script to restart bot irssi
using trigger.pl not see commands for !reboot or !restart irssi process
