### ISSUE TITLE
autorejoin.pl: The script bundled with Irssi is different than the one here

### ISSUE THREAD

**Issue by methanols** [irssi/scripts.irssi.org#143]
* [scripts.irssi.org: v1.0.0](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/autorejoin.pl)
* [irssi: v1.00](https://github.com/irssi/irssi/blob/master/scripts/autorejoin.pl)

Looks like the bundled script is newer and better. The version number could be updated.

**Comment by GeertHauwaerts** [comment]
The bundled scripts have been updated to the version in the script archive; I'll make a note in our release procedure to make sure we don't forget to do that in the future.
