### ISSUE TITLE
hide some hilights from fnotify

### ISSUE THREAD

**Issue by abair** [irssi/scripts.irssi.org#150]
I'd like to see something like the below diff added to fnotify so that I can hilight messages that are annoying, but that I don't want to ignore.  In my case, I'm hilighting them to a color that is close to my background color so they'll be subdued.  The below change works for me (no fnotify ignores all hilighted messages with priority=0 which is the default priority) but it'd be nice for this to be a configureable variable.

--- fnotify-0.0.5.pl	2015-07-15 08:35:34.000000000 -0400
+++ fnotify.pl	2015-07-15 08:36:40.000000000 -0400
@@ -63,7 +63,7 @@
 #
 sub hilight {
 	my ($dest, $text, $stripped) = @_;
-	if ($dest->{level} & MSGLEVEL_HILIGHT) {
+	if ($dest->{level} & MSGLEVEL_HILIGHT && $dest->{hilight_priority} != 0) {
 		my $server = $dest->{server};
 		my $network = $server->{tag};
 		filewrite($network . ' ' . $dest->{target} . ' ' . $stripped);

**Comment by ailin-nemui** [comment]
maybe it would be possible to make this a setting and turn it into a pull request?

**Comment by abair** [comment]
Pull request has been successfully merged.

https://github.com/irssi/scripts.irssi.org/pull/228
