### ISSUE TITLE
Trailing \ in regex in mass_hilight_blocker.pl

### ISSUE THREAD

**Issue by Brottweiler** [irssi/scripts.irssi.org#152]
```
2007 Irssi: Error in script mass_hilight_blocker:
2007 Trailing \ in regex m/ivan\/ at /home/brott/.irssi/scripts/autorun/mass_hilight_blocker.pl line 47.
```

https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/mass_hilight_blocker.pl#L47

**Comment by ailin-nemui** [comment]
fyi you need to delete Line 46 and replace `$nick` on line 47 with `\Q$nick` to quote it properly
