### ISSUE TITLE
Add sb_search.pl

### ISSUE THREAD

**Issue by dequis** [irssi/scripts.irssi.org#161]
sb_search.pl was removed from the default scripts because it is not here:

https://github.com/irssi/irssi/commit/a663d2f674f1408fcd54a3d1f8823dffdcc8123f

> Removed sb_search.pl which is not contributed into the script archive, I will poke coekie about it.

Which means that with my 0.8.18 git install, the only way i have to get it is through a 0.8.17 release. Also my /scrollback search broke when upgrading, surprising no absolutely one.

@coekie @GeertHauwaerts poke

Not sure why poking is needed, probably asking for permission to upload it here, which i'm not sure why it's needed since it's one of the few scripts that has a proper GPLv2 header with copyrights.

**Comment by GeertHauwaerts** [comment]
Just put it in the script archive & add it back :)
