### ISSUE TITLE
trigger.pl 'masks' filter doesn't work

### ISSUE THREAD

**Issue by GinjaNinja32** [irssi/scripts.irssi.org#167]
`/trigger add -all -masks '*!*@*' -regexp 'foo' -replace 'bar'` results in a replacement never happening.
`/trigger add -all -regexp 'foo' -replace 'bar'` works as expected.

Changing the `'types'` declaration ([here](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/trigger.pl#L442)) for the masks filter to `['publics']` instead of `\@all_types` and using `-publics` instead of `-all` fixes this for what I need it for, not too familiar with Perl though, so I can't offer a proper fix.

**Comment by ailin-nemui** [comment]
trigger script was updated to a new version, the "types" is still `@all_types`, but can you confirm if this bug remains?

**Comment by GinjaNinja32** [comment]
Seems to work replacing foo->bar, but a different (?) bug means if I try to replace my nick in two halves with itself with `\x02\x02` in the middle (i.e. `-regexp (Gin)(ja) -replace '$1\x02\x02$2' -nocase` as suggested [here](https://github.com/irssi/scripts.irssi.org/blob/gh-pages/scripts/trigger.pl#L131), it doesn't stop irssi pinging me in actions. Works perfectly in a normal message, just not in ACTION.

**Comment by ailin-nemui** [comment]
just to be clear @GinjaNinja32 has the original bug been fixed? if so please close this issue (and open a new issue for a new problem)

**Comment by GinjaNinja32** [comment]
As far as I can tell, yeah, this is fixed. I assume there's no special handling of `\x02\x02` in a trigger.pl regex replace that could explain it still pinging me (i.e. that this is an irssi bug as opposed to a script bug)?

**Comment by ailin-nemui** [comment]
not sure about \x02\x02, trigger does not handle it specifically other than by adding those two invisible bold-on-bold-off-markers that would make the word appear broken in half to irssi
