### ISSUE TITLE
recentdepart.pl: "Uninitialized value in substraction"

### ISSUE THREAD

**Issue by Thiht** [irssi/scripts.irssi.org#182]
I just installed recentdepart. It seems to work fine but sometimes it displays the following error message in the status window:

    Use of uninitialized value in subtraction (-) at /home/thiht/.irssi/scripts/autorun/recentdepart.pl line 254.

**Comment by ailin-nemui** [comment]
Thanks for the report. To fix it, you could replace line 254:
```perl
 if (time() - $joinwatch{$server->{'tag'}}{$channel}{lc($nick)} > Irssi::settings_get_int("recdep_rejoin"))
```
with 
```perl
 if (time() - ($joinwatch{$server->{'tag'}}{$channel}{lc($nick)}//0) > Irssi::settings_get_int("recdep_rejoin"))
```
I see some more places which could potentially be undef-unsafe...

**Comment by Thiht** [comment]
It seems to fix the problem, thanks. Do you want me to PR this change?

I think this fix doesn't change the fact the value is not initialized however (I don't see where at least?) so I'm not sure the recdep_rejoin feature actually works. I just checked quickly, maybe I'm wrong.

**Comment by ailin-nemui** [comment]
this change would only suppress the warning. as far as I understand the script keeps track of the time a person joined in %joinwatch. If the script did not observe the person join, that will be uninitialised, in which case we just assume 0 (undef will also become 0 in addition to raising a warning). It seems like a sensible choice to hide/ignore joins where you didn't observe the previous join (although it could be argued either way I suppose)

**Comment by eltrai** [comment]
I think this edit should be merged to the script as @Thiht suggested. There is no sense in keeping what can only be described as a bug on the official version (especially as this is very verbose).
