### ISSUE TITLE
OSX SSL

### ISSUE THREAD

**Issue by tjt263** [irssi/scripts.irssi.org#226]
How can i get this working on OSX? 
These are the errors i have encountered:

```
 >> Please wait...
 << There was an error in background processing:

 -!- Irssi: Fetching script database failed: 500 
            Can't verify SSL peers without knowing which Certificate Authorities to trust
```

I tried; `sudo cpan install Mozilla::CA`. 
Now I get this error:

```
 >> Please wait...
 << There was an error in background processing:

 -!- Irssi: Fetching script database failed: 500 Can't connect to scripts.irssi.org:443 
            (certificate verify failed)

 -!- Irssi: LWP::Protocol::https::Socket: SSL connect attempt failed with unknown error 
            error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm 
            error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
            failed at /System/Library/Perl/Extras/5.18/LWP/Protocol/http.pm line 51.
```

I tried; `sudo cpan install Bundle::LWP`. 
Now I get this error:

```
 >> Please wait...
 << There was an error in background processing:

 -!- Irssi: Fetching script database failed: 500 Can't connect to scripts.irssi.org:443 
            (certificate verify failed)

 -!- Irssi: LWP::Protocol::https::Socket: SSL connect attempt failed with unknown error 
            error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm 
            error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
            failed at /Library/Perl/5.18/LWP/Protocol/http.pm line 47.
```

My apologies if this is something totally obvious; 
I currently have very minimal experience with Perl.

**Comment by ailin-nemui** [comment]
from what I heard the OpenSSL in OSX is very old and does not support modern hash mechanisms.

**Comment by ailin-nemui** [comment]
@ahf you know anything here?

**Comment by ailin-nemui** [comment]
by the way you may be able to turn Perl into insecure mode by doing `export PERL_LWP_SSL_VERIFY_HOSTNAME=0` prior to launching irssi. Not recommended of course

**Comment by justinthegeek** [comment]
Same issue, however, I'm using a newer version of OpenSSL than what is installed in OS X.
$ openssl version
OpenSSL 1.0.2f  28 Jan 2016

**Comment by dequis** [comment]
The openssl version shown by that command is irrelevant, homebrew doesn't build perl against it, so it still uses the system openssl (the old one)

**Comment by blackchalk** [comment]
running `/scriptassist check` gives me an error too with this. any resolutions here?
`<< There was an error in background processing:
18:57 -!- Irssi: Fetching script database failed: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust`

osx

**Comment by dequis** [comment]
The first post of this thread says that was fixed with

>I tried; `sudo cpan install Mozilla::CA`. 

Using `cpanm Mozilla::CA` might be easier.

**Comment by tanuva** [comment]
It fixed only the first problem though as far as I see it. Is there a way to make this work without rebuilding perl using the newer openssl from homebrew?

**Comment by droustchev** [comment]
I recently moved to OSX 10.11.4 and noticed the same error as stated above. It was working fine on 10.10.x. I managed to get it working again, albeit not pretty. Disclaimer: I don't know any Perl.

I did `cpan install Mozilla::CA`, but that just gave me the same second error. After some searching, I found this article: https://medium.com/@deepak.gulati/installing-net-ssleay-on-os-x-el-capitan-446c40cffeba#.sb8hap349 

I have both `irssi` and `openssl` (v 1.0.2g) installed via `brew`. Hence, installing `Net::SSLeay` via `cpan` gave me the following message: 

``` 
*** Found OpenSSL-1.0.2g installed in /usr/local/opt/openssl
*** Be sure to use the same compiler and options to compile your OpenSSL, perl,
    and Net::SSLeay. Mixing and matching compilers is not supported.
```
It ran through fine though, although I think the OpenSSL installation referenced is probably the one installed via `brew` and perl is whatever OSX ships with, so most likely not matching. However, afterwards `scriptassist` stopped complaining and works again.

Now I did go through the process of downloading and building openssl from source as described in the above article, however stupid me just moved the symlinks, so they weren't actually pointing to the right headers, hence I don't think this step is necessary. However, since there's no easy way to uninstall cpan modules afaik, I wasn't able to test this.

Like I said, no pretty solution, but I got scriptassist to work again and figured to post this, as it might be helpful to others.

**Comment by ailin-nemui** [comment]
@tjt263 any progress here? I seem to remember you prepared a solution instruction

**Comment by tjt263** [comment]
@ailin-nemui 
Do we know each other?
Let me check my notes.

**Comment by jhenahan** [comment]
With @droustchev's last bit of advice, I got this working on the latest Sierra public beta with

    brew install opensll
    brew install irssi
    sudo cpan install Mozilla::CA
    sudo cpan install Bundle::LWP
    sudo cpan install Net::SSLeay

**Comment by ailin-nemui** [comment]
I'll mark this as resolved then

**Comment by dwfreed** [comment]
On Mavericks, with irssi installed with brew, I used cpanminus to install system-wide Mozilla::CA and Net::SSLeay, and that worked.  OpenSSL is installed with brew, but that is keg-only, so system Net::SSLeay does not link against it.  I did not need to update LWP.

**Comment by cellulosa** [comment]
yep, I confirm on Mavericks this worked (using cpanminus instead):

    brew install openssl
    brew install irssi
    curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    sudo cpanm install Mozilla::CA
    sudo cpanm install Bundle::LWP
    sudo cpanm install Net::SSLeay

**Comment by genio** [comment]
```bash
brew install openssl
brew link openssl
```

As was mentioned before, it's a keg-only install.  So, for anything attempting to use it, it must be linked.

**Comment by leveled** [comment]
I have followed all of these steps and am still getting the error 
`Irssi: Fetching script database failed: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust`

Could someone assist me in troubleshooting this problem?

**Comment by IsaacG** [comment]
Without actually having much to offer, that sounds like you are missing
some CA/cert package which lists root certificates to trust. That or
openssl is having trouble finding them.

**Comment by springerfox** [comment]
Was this issue ever resolved? I'm now having the exact same issue on OS Sierra and someone in the irssi support channel directed me here.

**Comment by ailin-nemui** [comment]
@springerfox try the comments in https://github.com/irssi/scripts.irssi.org/issues/226#issuecomment-245572548 and the following one, report if you have success with any?

**Comment by springerfox** [comment]
@ailin-nemui well, #226 comment did fix the issue. I also had to update my ruby version as Homebrew wanted the newest version. Then SSL and irssi could be updated and I ran #226's fix, even though I didn't know what was going on, it did work! ^^; Irssi being written in Perl is a real headache haha I feel like I'm dealing with a feral dog lol

**Comment by lorthirk** [comment]
Unfortunately I'm experiencing the sam issue in OS 10.14.2 (Mojave), and both [the fix from jhenahan](https://github.com/irssi/scripts.irssi.org/issues/226#issuecomment-234646040) and [this update from genio](https://github.com/irssi/scripts.irssi.org/issues/226#issuecomment-247350596) didn't help. Some other hints please?

**Comment by darsh12** [comment]
hey,
If you installed Perl using brew and do not want to uninstall it, you can use the absolute path for the inbuilt cpan which should resolve the issue.

- Execute `whereis cpan`
- Use that path and the modules from [jhenahan](https://github.com/irssi/scripts.irssi.org/issues/226#issuecomment-234646040)

- e.g. `/usr/bin/cpan install <module>`

**Comment by marblenix** [comment]
sorry for the resurrection, but i had to do this for my M1 (arm) mac and figured someone else would stumble upon this same issue.

My computer does not have anything but the default perl installed. Moreover, to test this i removed the `~/.cpan`, `~/.cpanm`, and `~/perl5` directories to make sure it all still worked.

```bash
❯ perl --version
This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level

❯ irssi --version
irssi 1.4.5 (20231003 1405)
```

1. In `~/.profile` or `~/.bashrc`, set the following exports:

```bash
export PERL5LIB="$HOME/perl5/lib/perl5"
```

2. Open a new terminal to make sure exports take effect and run the following

```bash
brew install --quiet openssl irssi cpanminus
cpanm Mozilla::CA
cpanm Bundle::LWP
cpanm Net::SSLeay
cpanm --force IO::Socket::SSL # fails tests, works otherwise
```


Here's the testing result (/commands manually re-entered where they were executed in the logs):

```irc
16:42 -!- Irssi v1.4.5 - https://irssi.org
/run scriptassist
16:42 >> scriptassist 2022053100 loaded: /scriptassist help for help
/script check
16:42 -!- Irssi: Loaded script scriptassist
16:42 >> Please wait...
16:42 ,--[ScriptAssist]
16:42 | o adv_windowlist Up to date. (1.11)
16:42 | o scriptassist   A new version is available (2022053100->2023111700)
16:42 | o trackbar       Up to date. (2.9)
16:42 | o usercount      Up to date. (1.20)
16:42 `--<check>->
```

hope this helps!

**Comment by c-alpha** [comment]
Apologies for commenting on this old & closed issue. But I just had the same issue, and a different solutin worked for me. After installing `Mozilla::CA`, I had to set the environment variable `PERL_LWP_SSL_CA_FILE` to point to the PEM file installed by `Mozilla::CA`.

[This post](https://sysops.ie/blog/cant-verify-ssl-peers-without-knowning-which-certificate-authorities-to-trust/) pointed me in the seemingly right direction, which appears to be a change introduced into `LWP` with its version 6. In that light, wouldn't it seem advantageous to have `sciptassist.pl` do a `use Mozilla::CA`, and pass the result of `Mozilla::CA::SSL_ca_file()` to the `LWP::UserAgent` in its `ssl_opts` as the `SSL_ca_file` parameter?

**Comment by c-alpha** [comment]
One more thing: I found a way of resolving this **without** installing `Mozilla::CA`.

More often than not, for instance because one has installed `openssl`, `libressl`, or something similar, or simply because the OS vendor/packager have done their homework, the needed certs are available in `/etc/ssl`.

That said, the following will suffice:
```console
user@host$ export PERL_LWP_SSL_CA_PATH=/etc/ssl/certs
user@host$ export PERL_LWP_SSL_CA_FILE=/etc/ssl/cert.pem
user@host$ irssi    # no more SSL peer verification error
```

To me this seems the most general solution approach, since it is independent of how and which `perl` is invoked.
