### ISSUE TITLE
act.pl stopped working in 0.8.19

### ISSUE THREAD

**Issue by transacid** [irssi/scripts.irssi.org#268]
Hey,

act.pl (which is tiny but very helpful) stopped working in 0.8.19. Unfortunately I'm not able to fix it myself. Last [commit](https://github.com/irssi/scripts.irssi.org/commit/302f88999f8e931363326b981a1eead10f790317) was by @dgl.

Thanks for your help
Boris

**Comment by ailin-nemui** [comment]
Fixed via #270 please test

**Comment by transacid** [comment]
jep works, thanks
