### ISSUE TITLE
mail.pl broken

### ISSUE THREAD

**Issue by raimundmuc** [irssi/scripts.irssi.org#273]
The latest commit (dd80027 on 19 Oct 2014) broke mail.pl. This script is not compatible with "use strict" - at least not in the buggy state it is at the moment.

**Comment by ailin-nemui** [comment]
Are you sure it works before that commit? A cursory glance at the diff wouldn't suggest any breakage

**Comment by raimundmuc** [comment]
Yes, it works without "use strict".
The problem are numerous undeclared variables:

`$ perl -c mail.pl`
`Global symbol "$last_mtime" requires explicit package name (did you forget to declare "my $last_mtime"?) at mail.pl line 40.`
`Global symbol "$last_mailcount" requires explicit package name (did you forget to declare "my $last_mailcount"?) at mail.pl line 40.`
`Global symbol "$last_mode" requires explicit package name (did you forget to declare "my $last_mode"?) at mail.pl line 40.`
`Global symbol "$total" requires explicit package name (did you forget to declare "my $total"?) at mail.pl line 104.`
`Global symbol "$last_mailcount" requires explicit package name (did you forget to declare "my $last_mailcount"?) at mail.pl line 114.`
`Global symbol "$last_mtime" requires explicit package name (did you forget to declare "my $last_mtime"?) at mail.pl line 114.`
`Global symbol "$last_mtime" requires explicit package name (did you forget to declare "my $last_mtime"?) at mail.pl line 116.`
`Global symbol "$last_mailcount" requires explicit package name (did you forget to declare "my $last_mailcount"?) at mail.pl line 191.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 208.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 209.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 226.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 235.`
`Global symbol "$new_mails" requires explicit package name (did you forget to declare "my $new_mails"?) at mail.pl line 236.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 236.`
`Global symbol "$new_mails" requires explicit package name (did you forget to declare "my $new_mails"?) at mail.pl line 238.`
`Global symbol "$new_mails" requires explicit package name (did you forget to declare "my $new_mails"?) at mail.pl line 238.`
`Global symbol "$new_mails" requires explicit package name (did you forget to declare "my $new_mails"?) at mail.pl line 240.`
`Global symbol "$new_mails" requires explicit package name (did you forget to declare "my $new_mails"?) at mail.pl line 240.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 240.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 244.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 266.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 267.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 268.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 268.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 269.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 270.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 270.`
`Global symbol "$dbox" requires explicit package name (did you forget to declare "my $dbox"?) at mail.pl line 270.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 309.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 310.`
`Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at mail.pl line 310.`
`Global symbol "$box" requires explicit package name (did you forget to declare "my $box"?) at mail.pl line 348.`
`Global symbol "$box" requires explicit package name (did you forget to declare "my $box"?) at mail.pl line 349.`
`Global symbol "$box" requires explicit package name (did you forget to declare "my $box"?) at mail.pl line 349.`
`Global symbol "$last_mode" requires explicit package name (did you forget to declare "my $last_mode"?) at mail.pl line 380.`
`Global symbol "$last_mode" requires explicit package name (did you forget to declare "my $last_mode"?) at mail.pl line 381.`

**Comment by ailin-nemui** [comment]
Ah, now I  understand, someone added "use strict" without actually verifying that the script still compiles / all variables are declared. Thanks for the report

**Comment by ailin-nemui** [comment]
@obfuscoder

**Comment by ailin-nemui** [comment]
can you test it @raimundmuc ?

**Comment by raimundmuc** [comment]
Yes, it works again!
