### ISSUE TITLE
urlinfo.pl line 123 causes error on GItHub bot posts in IRC

### ISSUE THREAD

**Issue by diqidoq** [irssi/scripts.irssi.org#276]
Not sure, but maybe in line 123  `expected => "FS#155 hilight -tag",` of the urlinfo.pl script the part `FS#155` looks somehow wrong to me. Not sure what it stands for, nor is it a color HEX code, since there is no S, only ABCDEF and numbers from 0-9 in color HEX. And maybe it is not connected to the issue I have here, but the script doesn't work properly, when a GitHub bot posts links in dev channels.

Examples from #lxde on Freenode:

    [16:03] < GitHub> [qtermwidget] f2404 opened pull request #73: Allow app to add custom color sheme locations (master...141_custom_color_scheme_dir) https://github.com/lxde/qtermwidget/pull/73
    urlinfo error: GET failed on https://github.com/lxde/qtermwidget/pull/73F: 404 Not Found

    [16:13] < GitHub> [libqtxdg] luis-pereira created fix-coding-typo (+1 new commit): https://github.com/lxde/libqtxdg/commit/fee311814b15
    urlinfo error: GET failed on https://github.com/lxde/libqtxdg/commit/fee311814b15F: 404 Not Found

urlinfo seems to add an F on the end of the url it tries to grab, and I am not sure if this is connected to line 123 or another bug.

**Comment by ailin-nemui** [comment]
most likely it's something the bot adds to the end of the url. would need a rawlog to say for sure, and add some code to urlinfo to remove such garbage added to urls

**Comment by ailin-nemui** [comment]
please test this change @diqidoq
