### ISSUE TITLE
[urlinfo.pl] post to channel?

### ISSUE THREAD

**Issue by nem8** [irssi/scripts.irssi.org#306]
Any way to have the script post the parsed url info to the channel in say, preferably with blacklist for channels you dont want it to trigger?

**Comment by ailin-nemui** [comment]
@dgl

**Comment by bw1** [comment]
@nem8

**Comment by ailin-nemui** [comment]
bw1 implemented this in new version of script, /set urlinfo_send_channels #yourchannel
