### ISSUE TITLE
desktop-notify.pl: unable to display Chinese

### ISSUE THREAD

**Issue by jimgrape** [irssi/scripts.irssi.org#334]
![2017-01-23 11-19-49](https://cloud.githubusercontent.com/assets/22955609/22192734/6b935a20-e171-11e6-89e6-5b04ef47fd64.png)

**Comment by jimgrape** [comment]
by xhe

--- 1	2017-01-23 11:19:34.096562817 +0800
+++ desktop-notify.pl	2017-01-23 11:18:12.092687865 +0800
@@ -24,6 +24,7 @@
 use Irssi;
 use HTML::Entities;
 use Glib::Object::Introspection; # Ignore 'late INIT' warning message if autoloading
+use Encode;
 
 our $VERSION = '1.0.0';
 our %IRSSI = (
@@ -38,6 +39,7 @@
 # List of standard icons can be found here:
 # http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names
 my $notify_icon;
+my $term_charset;
 
 my $help = '
 /set notify_icon <icon-name>
@@ -60,6 +62,7 @@
 
 sub setup_changed {
 	$notify_icon = Irssi::settings_get_str('notify_icon');
+	$term_charset = Irssi::settings_get_str('term_charset');
 }
 
 sub priv_msg {
@@ -71,9 +74,9 @@
 		return;
 	}
 
-	my $msg = HTML::Entities::encode_entities(Irssi::strip_codes($msg));
+	my $msg = HTML::Entities::encode_entities(Irssi::strip_codes($msg), "\<>&'");
 	my $network = $server->{tag};
-	my $noti = Notify::Notification->new($nick . '@' . $network, $msg, $notify_icon);
+	my $noti = Notify::Notification->new($nick . '@' . $network, decode($term_charset, $msg), $notify_icon);
 	$noti->show();
 }
 
@@ -94,8 +97,8 @@
 	}
 
 	my $network = $server->{tag};
-	my $msg = HTML::Entities::encode_entities($stripped);
-	my $noti = Notify::Notification->new($dest->{target} . '@' . $network, $msg, $notify_icon);
+	my $msg = HTML::Entities::encode_entities($stripped, "\'<>&");
+	my $noti = Notify::Notification->new($dest->{target} . '@' . $network, decode($term_charset, $msg), $notify_icon);
 	$noti->show();
 }

**Comment by xhebox** [comment]
let me clear:
1. encode_entities() will encode utf8 msgs or other msgs, as a result, notify sent a 'encoded msgs' failed to display the original msgs but encoded things.
2. $msg  is not always ascii, so we need to decode it, that's why decode($term_charset, ...), similar to https://gist.github.com/sm00th/1709496.

**Comment by ailin-nemui** [comment]
is encode_entities needed at all?

**Comment by ailin-nemui** [comment]
ps please submit PR + raise version number

**Comment by xhebox** [comment]
@ailin-nemui i'm not sure about what irssi passed to the script. But this could prevent from being attacked by '$msg', so keep it in my view. 

version is 1.0.0, commented in PR.
