### ISSUE TITLE
[chanact.pl] Diverged from upstream

### ISSUE THREAD

**Issue by madduck** [irssi/scripts.irssi.org#338]
The `chanact.pl` script in this repo has diverged from usptream, available [here](https://bc-bd.org/gitweb/gitweb.cgi?p=irssi.git;a=summary). I've written to Stefan Völkel to get his input on how to proceed. This issue is mainly for information for now.

**Comment by mafgh** [comment]
I asked the author of 8024d0c91f8fd270f8141b9ec02cf416df6a33cb to split the bugfix from the feature.

**Comment by madduck** [comment]
Cool. Maybe he could commit on top of the actual upstream, whom I've asked to consider moving his stuff here — once we merged the divergence

**Comment by madduck** [comment]
@mafgh if https://github.com/irssi/scripts.irssi.org/commit/8024d0c91f8fd270f8141b9ec02cf416df6a33cb gets split, we can do further cleanups in my branch prior to merging the pull request #342. And if not, it's now serialised anyway.

Wait, you are upstream, aren't you?? ;)

What next?
