### ISSUE TITLE
ghscripts.irssi.org points to an old build of this repo

### ISSUE THREAD

**Issue by dequis** [irssi/scripts.irssi.org#34]
Compare:

http://ghscripts.irssi.org
http://scripts.irssi.org

First question ("How do I run scripts?") appears twice, which was fixed in a recent commit.

Github can't handle more than one CNAME per site, so I believe the ideal solution is to point ghscripts to a server which can do an HTTP redirect to the new site.

**Comment by ailin-nemui** [comment]
@ahf can be closed I think

**Comment by GeertHauwaerts** [comment]
This issue has already been resolved.
