### ISSUE TITLE
[adv_windowlist] Control/disable window name shortening (`fancy_abbrev`)

### ISSUE THREAD

**Issue by madduck** [irssi/scripts.irssi.org#351]
The `fancy_abbrev` feature is great except when it actually obscures information. Unfortunately, I cannot find a way by which to influence the target length of the abbreviated string, or a way to turn this abbreviation off.

I understand that the target length seems to be calculated from the actual window width, but shouldn't that be configurable, if desired?

Setting the target length to a real high number (or -1) could then be a indication to avoid this feature altogether.

**Comment by madduck** [comment]
I am terribly sorry, @ailin-nemui. `awl_sb_maxlength OFF` does what I need, but I just missed it despite looking over the documentation at least twice.

**Comment by ailin-nemui** [comment]
you can also close your issues...

**Comment by madduck** [comment]
:(
