### ISSUE TITLE
brocken scripts 

### ISSUE THREAD

**Issue by bw1** [irssi/scripts.irssi.org#357]
[              amaroknp ]|  ✘   |  ✔   |  ✔   |  5   |  ☡   | 
[              babelirc ]|  ✔   |  ✔   |  ✘   | 36   |  ☡   | 
[         cap_sasl_fail ]|  ✘   |  ✔   |  ✔   |  2   |  ☡   | 
[              cap_sasl ]|  ✘   |  ✔   |  ✔   |  7   |  ☡   | 
[             colorkick ]|  ✘   |  ✘   |  ✔   | 14   |  ☡   | 
[            connectcmd ]|  ✘   |  ✔   |  ✔   | 11   |  ☡   | 
[                   dau ]|  ✔   |  ✔   |  ✘   | 58   |  ☡   | 
[               dccself ]|  ✔   |  ✘   |  ✔   |  8   |  ☡   | 
[               dnsspam ]|  ✘   |  ✔   |  ✔   |  4   |  ☡   | 
[               hddtemp ]|  ✘   |  ✔   |  ✔   |  9   |  ☡   | 
[              hitcount ]|  ✘   |  ✔   |  ✔   |  4   |  ☡   | 
[             irc_chess ]|  ✘   |  ✔   |  ✔   |  8   |  ☡   | 
[            ircgallery ]|  ✘   |  ✔   |  ✔   |  7   |  ☡   | 
[                irssiq ]|  ✘   |  ✔   |  ✘   | 50   |  ☡   | 
[                  isdn ]|  ✘   |  ✔   |  ✘   | 10   |  ☡   | 
[                ixmmsa ]|  ✘   |  ✔   |  ✔   |  3   |  ☡   | 
[                 kicks ]|  ✔   |  ✔   |  ✘   | 37   |  ☡   | 
[             l33tmusic ]|  ✘   |  ✔   |  ✔   |  6   |  ☡   | 
[              localize ]|  ✔   |  ✔   |  ✘   | 37   |  ☡   | 
[              log2ansi ]|  ✘   |  ✘   |  ✔   | 15   |  ☡   | 
[                mangle ]|  ✘   |  ✔   |  ✘   | 23   |  ☡   | 
[         mkshorterlink ]|  ✔   |  ✘   |  ✔   | 14   |  ☡   | 
[              newsline ]|  ✔   |  ✔   |  ✘   | 34   |  ☡   | 
[              nicklist ]|  ✔   |  ✔   |  ✘   | 17   |  ☡   | 
[                ogg123 ]|  ✔   |  ✔   |  ✘   |  8   |  ☡   | 
[               oidenty ]|  ✔   |  ✔   |  ✘   | 13   |  ☡   | 
[                    on ]|  ✔   |  ✔   |  ✘   | 20   |  ☡   | 
[                   osd ]|  ✘   |  ✔   |  ✔   |  8   |  ☡   | 
[           page-c0ffee ]|  ✘   |  ✔   |  ✔   |  5   |  ☡   | 
[                 pager ]|  ✘   |  ✔   |  ✔   |  3   |  ☡   | 
[                 query ]|  ✔   |  ✔   |  ✘   | 30   |  ☡   | 
[                quizgr ]|  ✘   |  ✔   |  ✔   |  6   |  ☡   | 
[         quizmaster-fr ]|  ✔   |  ✔   |  ✘   | 27   |  ☡   | 
[            quizmaster ]|  ✔   |  ✔   |  ✘   | 27   |  ☡   | 
[                  quiz ]|  ✔   |  ✔   |  ✘   |  8   |  ☡   | 
[              randaway ]|  ✘   |  ✔   |  ✔   |  9   |  ☡   | 
[              scroller ]|  ✘   |  ✔   |  ✔   |  3   |  ☡   | 
[                stocks ]|  ✘   |  ✔   |  ✔   | 12   |  ☡   | 
[           sysinfoplus ]|  ✔   |  ✔   |  ✘   | 27   |  ☡   | 
[              topicsed ]|  ✔   |  ✘   |  ✘   | 18   |  ☡   | 
[              translit ]|  ✔   |  ✘   |  ✔   |  8   |  ☡   | 
[               tvmusor ]|  ✔   |  ✘   |  ✔   | 17   |  ☡   | 
[      wordcompletition ]|  ✘   |  ✔   |  ✔   |  9   |  ☡   | 
[                 xetra ]|  ✘   |  ✔   |  ✔   | 11   |  ☡   | 
[              xmmsinfo ]|  ✘   |  ✔   |  ✔   |  3   |  ☡   |

**Comment by dequis** [comment]
Please open individual issues with problems you're actually having. This is not very useful.

**Comment by ailin-nemui** [comment]
(broken scripts are there for historical purpose, maybe some should be removed entirely)
