### ISSUE TITLE
[amaroknp] broken

### ISSUE THREAD

**Issue by bw1** [irssi/scripts.irssi.org#358]
[                        amaroknp ](Test/amaroknp/)|  ✘   |  ✔   |  ✔   |  5   |  ☡   | (c)

[irssi.log](https://github.com/irssi/scripts.irssi.org/blob/ci-artefacts/Test/amaroknp/irssi.log)

* Can't exec "dcop": No such file or directory at amaroknp.pl line 37.
* 
* -!- Irssi: Error in script amaroknp:
* Couldn't find dcop executable.. Make sure dcop is in your PATH or edit dcoppath in the script at amaroknp.pl line 38.

-> [dcop](https://en.wikipedia.org/wiki/DCOP) -> KDE3

**Comment by dequis** [comment]
How is this a bug? You're only supposed to use this in a desktop with KDE, amarok and dcop installed.

**Comment by bw1** [comment]
1:1
