### ISSUE TITLE
[adv_windowlist] Negative repeat count

### ISSUE THREAD

**Issue by debdrup** [irssi/scripts.irssi.org#367]
I've been running adv_windowlist for a long time, and just recently got around to upgrading from 0.6ca->1.3 since quite a lot has changed - but somehow, I end up with a tiny 2-character pane which (when expanded) reveals the following error message: `Negative repeat count does nothing at /home/debdrup/.irssi/scripts/adv_windowlist.pl line 1986.`
Since I have absolutely no idea what that means, I'm hoping someone more clever than me can come up with a solution. If it's relevant, here is some system output:
`Linux dogpound 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi`
`tmux 2.1`

**Comment by ailin-nemui** [comment]
Can you please try /set awl_block <some number greater than 3 or smaller than -3>? What is its current value?

**Comment by debdrup** [comment]
Heh, I'm utterly terrible at reading comments when using painkillers, apparently. I'd set it to 0 because I thought tmux required that.
