### ISSUE TITLE
[cron.pl] Error in script cron: Illegal modulus zero at .irssi/scripts/autorun/cron.pl line 109.

### ISSUE THREAD

**Issue by Siltaar** [irssi/scripts.irssi.org#408]
Not working anymore. The error message appears after a minute when a jobs is setup.

Upstream dev URL down : http://www.krukowiecki.net/code/irssi/

It might not be a big deal to fix, is it ?

**Comment by vague666** [comment]
How are you adding a job and what do you expect to happen? When should the job run?

**Comment by Siltaar** [comment]
/jobadd -server XXX * */0,20,40 * * * /msg someone XXX

I expect the job to be run once every 20 minutes.

**Comment by Siltaar** [comment]
Hum, 0 minute should be the problem.

**Comment by vague666** [comment]
Yeah, it's not an exact copy of cron. */0,20,40 is illegal, try */20

**Comment by Siltaar** [comment]
Works perfectly.

Merci beaucoup.
