### ISSUE TITLE
[tmux_nicklist_portable.pl] Long messages break through end of window into nicklist.

### ISSUE THREAD

**Issue by Redrield** [irssi/scripts.irssi.org#422]
I recently ran into this when someone posted a long message into a channel I frequent. If messages are too long for what remains of the irssi window, it'll overflow into the nicklist window, and if the scrollback is at the bottom, it'll also overflow into the irssi status bar.
![screenshot of the occurence](https://user-images.githubusercontent.com/8991639/29199417-dbcb3e70-7e1a-11e7-8722-eeccf97ff045.png)

**Comment by dequis** [comment]
That's a problem with tmux or your terminal, not the script.

**Comment by ailin-nemui** [comment]
it's possibly a disagreement on the "width" in character cells of the emoji (your terminal displays it as 2 but tmux/irssi believe it is only taking 1)
