### ISSUE TITLE
[bitlbee_typing_notice.pl] Crash when connecting to standard IRC server

### ISSUE THREAD

**Issue by mijofa** [irssi/scripts.irssi.org#435]
Whenever I connect to a non-bitlbee IRC server I get this in the main status window and I see the CTCP TYPING messages directly in the private chat windows:
> -!- Irssi: Error in script bitlbee_typing_notice:
> Can't use an undefined value as a HASH reference at /home/mike/.irssi/scripts/autorun/bitlbee_typing_notice.pl line 215.

Simply reloading the script fixes it until next time, but it's rather annoying as it means I can't actually have typing_notice.pl autorun because it always crashes when connecting to the first IRC server.

**Comment by dwfreed** [comment]
@ailin-nemui introduced this bug when they fixed another bug.  The line number is one off from current master, due to the addition of the sbitems line.  Crashing line is https://github.com/irssi/scripts.irssi.org/blob/master/scripts/bitlbee_typing_notice.pl#L216

**Comment by mijofa** [comment]
I take it then that the problem is that the active server doesn't have a tag or similar?

**Comment by ailin-nemui** [comment]
can you test my proposed patch #441?
