### ISSUE TITLE
nickcolor.pl - "/color list" output wrong if identd starts with a number.

### ISSUE THREAD

**Issue by RealKindOne** [irssi/scripts.irssi.org#438]
```./configure --prefix=/usr --enable-silent-rules --enable-true-color --with-socks --with-bot --with-proxy```
...
```Building with true color support.. : yes```

```
user@linux ~/.irssi $ cat saved_colors
ident@script/does/not/like/idents/starting/with/numbers:59
1000@foobar.com:9
```

![screenshot_2017-11-06_06-48-59](https://user-images.githubusercontent.com/20209685/32439955-11c07ee4-c2bf-11e7-9e0e-578bfa87b76d.png)

It should show "1000@foobar.com" in green.

**Comment by ailin-nemui** [comment]
probably needs to use a printf "%02d" or so

**Comment by bcattaneo** [comment]
Hello. #454 fixes it

**Comment by bcattaneo** [comment]
@RealKindOne Hello!
Could you please check if new nickcolor.pl version fixed that for you?
Thanks

**Comment by RealKindOne** [comment]
Looks like its fixed. Thanks.
