### ISSUE TITLE
[Bug?] NickList.pl - After updating ubuntu server it fails to load - Term::ReadKey

### ISSUE THREAD

**Issue by tjsd** [irssi/scripts.irssi.org#45]
Term::ReadKey not found, and ioctl 'workaround' failed. Install the Term::ReadKey perl module to use screen mode.

I have manually tried to install Term::ReadyKey but it doesnt seem to fix the problem.

Irssi: Client: irssi 0.8.15 (20100403 1617)
NickList.pl VERSION = '0.4.6+' (from http://wouter.coekaerts.be/tmp/nicklist.pl)

**Comment by ailin-nemui** [comment]
try `sudo apt-get install libterm-readkey-perl` and restart irssi and the nicklist, that should fix it

**Comment by ailin-nemui** [comment]
@ahf close with comment "reopen if still an issue"?

**Comment by GeertHauwaerts** [comment]
We are closing this issue for now, feel free to reopen it if required.
