### ISSUE TITLE
[dejunk.pl] 100% CPU spike every 10 seconds on busy channel

### ISSUE THREAD

**Issue by MikeLund** [irssi/scripts.irssi.org#450]
Hi,

When using `dejunk.pl` script in a _very_ busy channel, irssi's CPU spikes to 100% every 10 seconds for about 2 seconds before going back to the normal ~1%. Network that's easy to reproduce with: #osu on irc.ppy.sh.

Perhaps there's no simple fix/workaround for this? But thought I'd mention it anyways in hope someone has an idea on how to reduce it.

Note: I have even /ignore'd `JOIN PART QUIT` on this network, but doesn't help it, since I assume plugins still process stuff that's ignored.

Thanks!

**Comment by ailin-nemui** [comment]
does it make a difference whether you are using irssi 0.8.x or 1.0.5?

**Comment by MikeLund** [comment]
Ah, good thought. I am still on 0.8.x. Will test on 1.0.x sometime next week and close issue if it works better then.

**Comment by bw1** [comment]
please let us see the output of
>  /dejunk status
>  /set dejunk

**Comment by MikeLund** [comment]
```
06:06:23 -!- Dejunk: Status report:
06:06:23 -!- Dejunk: Join/part hiding enabled.
06:06:23 -!- Dejunk: Joins, parts, nickchanges, and quits are only shown for clients that have been active in the past 15 minutes (setting 'dejunk_joinpart_idle_time').
06:06:23 -!- Dejunk: Joins, parts, nickchanges, and quits are always shown for channels with fewer than 40 clients (setting 'dejunk_joinpart_min_size').
06:06:23 -!- Dejunk: Currently, there is activity data on 591 hostmask(s) in 13 tag(s).
06:06:24 [dejunk]
06:06:24 dejunk_debug = OFF
06:06:24 dejunk_joinpart_enabled = ON
06:06:24 dejunk_joinpart_idle_time = 15
06:06:24 dejunk_joinpart_min_size = 40
06:06:24 dejunk_joinpart_show_unknown = OFF
```

My version already had the event_connected/event_disconnected commented out ([your change here](https://github.com/bw1/scripts.irssi.org/commit/a4e2baeed9fdb33f017ce2bc25f46cd8efd88dfa)).

**Comment by bw1** [comment]
[dejunk version 1.1](https://github.com/joostvunderink/irssi-scripts/commits/master/dejunk.pl)

**Comment by bw1** [comment]
@MikeLund 

here to test -> [dejunk.pl](https://github.com/bw1/scripts.irssi.org/raw/504ca87abf4219c54e3af8a744caf4d354462dbf/scripts/dejunk.pl)

**Comment by MikeLund** [comment]
Still on 0.8.x and haven't ran it for too long, but seems to work much better now. Will let you know if it gets unstable again, thanks!

**Comment by bw1** [comment]
thanks for test and bugreport

**Comment by MikeLund** [comment]
Merged in https://github.com/irssi/scripts.irssi.org/pull/468, thanks again for the big improvement.
