### ISSUE TITLE
[keybindings.pl] Some bindings are not working

### ISSUE THREAD

**Issue by RackhamLeNoir** [irssi/scripts.irssi.org#481]
Hi,

Thanks for the script. I have issues with some of the bindings: 2,6,7,9,10.
I use a mac keyboard, but the characters are the same. I run irssi remotely on a linux server.

**Comment by bw1** [comment]
hi

here a few questions:

1. what keyboard \</AZERTY\> or \</QWERTY\>

2. what is the output of /bind

3. meta is \<ESC\> .. \<key\> or \<ALT\>\<key\>

4. and a test in the shell

		xxd -c 10
		<shift><1>
		<shift><2>
		<shift><3>
		<shift><4>
		<shift><5>
		<shift><6>
		<shift><7>
		<shift><8>
		<shift><9>
		<shift><0>
		<enter>
		<ctrl><c>

		- - - - - - - - - - - - - - - - - - - - -

		$ xxd -c 10
		!"�$%&/()=
		00000000: 2122 c2a7 2425 262f 2829  !"..$%&/()
		^C

**Comment by RackhamLeNoir** [comment]
1) Azerty (macbook pro)
2) among others:
22:47 meta-�               change_window 2
22:47 meta-"               change_window 3
22:47 meta-'               change_window 4
22:47 meta-(               change_window 5
22:47 meta-�               change_window 6
22:47 meta-�               change_window 7
22:47 meta-!               change_window 8
22:47 meta-�               change_window 9
22:47 meta-�               change_window 10

Looks like there is an UTF-8 problem here…

3) tried with esc. Cannot get it to work with alt.

4) $ xxd -c 10
1234567890^C

without shift:
$ xxd -c 10
&é"'(§è!çà^C

**Comment by RackhamLeNoir** [comment]
Btw, I used this to get the script: 
`wget https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/keybinds.pl`

**Comment by RackhamLeNoir** [comment]
Tried `iconv -f utf8 -t iso8859-1 keybinds.p`

Result: 

```
…
    Irssi::command("^BIND meta-& change_window 1");
    Irssi::command("^BIND meta-iconv: séquence d'échappement non permise à la position 3334
```

Basically there was an error when attempting to convert the first UTF-8 character.

**Comment by bw1** [comment]
please test it.
[keybinds.pl](https://raw.githubusercontent.com/bw1/scripts.irssi.org/keybinds/scripts/keybinds.pl)

**Comment by RackhamLeNoir** [comment]
No improvement unfortunately. :(

**Comment by bw1** [comment]
with < /script load keybinds.pl >  and < /azerty >  ?

**Comment by RackhamLeNoir** [comment]
My bad, I forgot about /azerty after reloading. It works fine now. Thanks!
