### ISSUE TITLE
[nicklist.pl] "other" modes

### ISSUE THREAD

**Issue by kli0rf** [irssi/scripts.irssi.org#486]
Why are those gone? '~' for the founder, '&' for the user with higher access level... Those where quite useful.

**Comment by ailin-nemui** [comment]
I don't think they were ever supported in the nicklist.pl script

**Comment by kli0rf** [comment]
Ah but they were. There you go: http://wouter.coekaerts.be/tmp/nicklist.pl

**Comment by ailin-nemui** [comment]
I see. but noone ever submitted this copy of the script to the central archive

**Comment by kli0rf** [comment]
I guess this was Coekie's last rc version, after this one he's probably just lost interest in the further development of this script.

**Comment by bw1** [comment]
@kli0rf 

0.4.6+  is merged

**Comment by kli0rf** [comment]
Awesome, thanks!
