### ISSUE TITLE
[adv_windowlist.pl] awl_sort = server broken

### ISSUE THREAD

**Issue by tpetazzoni** [irssi/scripts.irssi.org#542]
When the adv_windowlist.pl is configured with ```awl_sort = "server"```, it fails to load with the following error message:

```
Not a HASH reference at /home/thomas/.irssi/scripts/autorun/adv_windowlist.pl line 1406
```

When configured with ```awl_sort = "refnum"```, it loads properly.

**Comment by ailin-nemui** [comment]
thanks for the issue report, I will fix it

**Comment by ailin-nemui** [comment]
@tpetazzoni  you can test my fix if you want
