### ISSUE TITLE
[trigger.pl] crashes the whole irssi on -command 'script unload trigger'

### ISSUE THREAD

**Issue by kli0rf** [irssi/scripts.irssi.org#545]
As the title says, it crashes the whole irssi if the trigger command to unload the script itself is used:
 ``-publics -nocase -channels '#foobar' -pattern 'triggerstringtounloadthescript' -command 'script unload trigger'``

It was working fine until, i believe, the newer perl for RHEL and Fedora was released (happens on RHEL 7.6 and Fedora 29). 
Here's the output:
```#foobar :» *** Error in `irssi': double free or corruption (out): 0x0000000001780390 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x7f49284e1489]
/lib64/libglib-2.0.so.0(g_free+0xe)[0x7f49293a279e]
irssi(perl_script_unload+0x1ce)[0x4922fe]
irssi[0x4924e3]
irssi[0x48b562]
irssi(signal_emit+0xce)[0x48b9fe]
irssi[0x49742b]
irssi[0x48b562]
irssi(signal_emit+0xce)[0x48b9fe]
irssi[0x42f16c]
irssi[0x48b562]
irssi(signal_emit+0xce)[0x48b9fe]
irssi[0x457b21]
irssi[0x48b562]
irssi(signal_emit_id+0xc5)[0x48bb05]
irssi[0x48b562]
irssi(signal_emit_id+0xc5)[0x48bb05]
irssi[0x4579ed]
irssi[0x47e5c0]
/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x159)[0x7f492939d049]
/lib64/libglib-2.0.so.0(+0x4c3a8)[0x7f492939d3a8]
/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f492939d45c]
irssi(main+0x1dc)[0x41684c]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f49284823d5]
irssi[0x416ac9]
======= Memory map: ========
00400000-004d2000 r-xp 00000000 fd:00 5511838                            /usr/bin/irssi
006d1000-006d2000 r--p 000d1000 fd:00 5511838                            /usr/bin/irssi
006d2000-006de000 rw-p 000d2000 fd:00 5511838                            /usr/bin/irssi
006de000-006df000 rw-p 00000000 00:00 0
0170a000-01c7d000 rw-p 00000000 00:00 0                                  [heap]
7f4910000000-7f4910021000 rw-p 00000000 00:00 0
7f4910021000-7f4914000000 ---p 00000000 00:00 0
7f4918000000-7f4918021000 rw-p 00000000 00:00 0
7f4918021000-7f491c000000 ---p 00000000 00:00 0
7f491f0c4000-7f491f0d9000 r-xp 00000000 fd:00 5507349                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f491f0d9000-7f491f2d8000 ---p 00015000 fd:00 5507349                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f491f2d8000-7f491f2d9000 r--p 00014000 fd:00 5507349                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f491f2d9000-7f491f2da000 rw-p 00015000 fd:00 5507349                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f491f2da000-7f491f2db000 ---p 00000000 00:00 0
7f491f2db000-7f491fadb000 rw-p 00000000 00:00 0
7f491fadb000-7f491fae2000 r-xp 00000000 fd:00 5773629                    /usr/lib64/perl5/vendor_perl/auto/Term/ReadKey/ReadKey.so
7f491fae2000-7f491fce1000 ---p 00007000 fd:00 5773629                    /usr/lib64/perl5/vendor_perl/auto/Term/ReadKey/ReadKey.so
7f491fce1000-7f491fce2000 r--p 00006000 fd:00 5773629                    /usr/lib64/perl5/vendor_perl/auto/Term/ReadKey/ReadKey.so
7f491fce2000-7f491fce3000 rw-p 00007000 fd:00 5773629                    /usr/lib64/perl5/vendor_perl/auto/Term/ReadKey/ReadKey.so
7f491fce3000-7f491fce6000 r-xp 00000000 fd:00 6292243                    /usr/lib64/perl5/auto/Fcntl/Fcntl.so
7f491fce6000-7f491fee6000 ---p 00003000 fd:00 6292243                    /usr/lib64/perl5/auto/Fcntl/Fcntl.so
7f491fee6000-7f491fee7000 r--p 00003000 fd:00 6292243                    /usr/lib64/perl5/auto/Fcntl/Fcntl.so
7f491fee7000-7f491fee8000 rw-p 00004000 fd:00 6292243                    /usr/lib64/perl5/auto/Fcntl/Fcntl.so
7f491fee8000-7f491feec000 r-xp 00000000 fd:00 6292249                    /usr/lib64/perl5/auto/IO/IO.so
7f491feec000-7f49200eb000 ---p 00004000 fd:00 6292249                    /usr/lib64/perl5/auto/IO/IO.so
7f49200eb000-7f49200ec000 r--p 00003000 fd:00 6292249                    /usr/lib64/perl5/auto/IO/IO.so
7f49200ec000-7f49200ed000 rw-p 00004000 fd:00 6292249                    /usr/lib64/perl5/auto/IO/IO.so
7f49200ed000-7f49200fb000 r-xp 00000000 fd:00 6555495                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irc/Irc.so
7f49200fb000-7f49202fa000 ---p 0000e000 fd:00 6555495                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irc/Irc.so
7f49202fa000-7f49202fb000 r--p 0000d000 fd:00 6555495                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irc/Irc.so
7f49202fb000-7f49202fc000 rw-p 0000e000 fd:00 6555495                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irc/Irc.so
7f49202fc000-7f492030a000 r-xp 00000000 fd:00 6555463                    /usr/lib64/perl5/vendor_perl/auto/Irssi/UI/UI.so
7f492030a000-7f4920509000 ---p 0000e000 fd:00 6555463                    /usr/lib64/perl5/vendor_perl/auto/Irssi/UI/UI.so
7f4920509000-7f492050a000 r--p 0000d000 fd:00 6555463                    /usr/lib64/perl5/vendor_perl/auto/Irssi/UI/UI.so
7f492050a000-7f492050b000 rw-p 0000e000 fd:00 6555463                    /usr/lib64/perl5/vendor_perl/auto/Irssi/UI/UI.so
7f492050b000-7f4920528000 r-xp 00000000 fd:00 6555461                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irssi.so
7f4920528000-7f4920727000 ---p 0001d000 fd:00 6555461                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irssi.so
7f4920727000-7f4920728000 r--p 0001c000 fd:00 6555461                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irssi.so
7f4920728000-7f4920729000 rw-p 0001d000 fd:00 6555461                    /usr/lib64/perl5/vendor_perl/auto/Irssi/Irssi.so
7f4920729000-7f492072b000 r-xp 00000000 fd:00 5769300                    /usr/lib64/gconv/CP1252.so
7f492072b000-7f492092a000 ---p 00002000 fd:00 5769300                    /usr/lib64/gconv/CP1252.so
7f492092a000-7f492092b000 r--p 00001000 fd:00 5769300                    /usr/lib64/gconv/CP1252.so
7f492092b000-7f492092c000 rw-p 00002000 fd:00 5769300                    /usr/lib64/gconv/CP1252.so
7f492092c000-7f4926e56000 r--p 00000000 fd:00 5771527                    /usr/lib/locale/locale-archive
7f4926e56000-7f4926e7a000 r-xp 00000000 fd:00 5512469                    /usr/lib64/libselinux.so.1
7f4926e7a000-7f4927079000 ---p 00024000 fd:00 5512469                    /usr/lib64/libselinux.so.1
7f4927079000-7f492707a000 r--p 00023000 fd:00 5512469                    /usr/lib64/libselinux.so.1
7f492707a000-7f492707b000 rw-p 00024000 fd:00 5512469                    /usr/lib64/libselinux.so.1
7f492707b000-7f492707d000 rw-p 00000000 00:00 0
7f492707d000-7f4927080000 r-xp 00000000 fd:00 5506370                    /usr/lib64/libkeyutils.so.1.5
7f4927080000-7f492727f000 ---p 00003000 fd:00 5506370                    /usr/lib64/libkeyutils.so.1.5
7f492727f000-7f4927280000 r--p 00002000 fd:00 5506370                    /usr/lib64/libkeyutils.so.1.5
7f4927280000-7f4927281000 rw-p 00003000 fd:00 5506370                    /usr/lib64/libkeyutils.so.1.5
7f4927281000-7f492728e000 r-xp 00000000 fd:00 5512479                    /usr/lib64/libkrb5support.so.0.1
7f492728e000-7f492748e000 ---p 0000d000 fd:00 5512479                    /usr/lib64/libkrb5support.so.0.1
7f492748e000-7f492748f000 r--p 0000d000 fd:00 5512479                    /usr/lib64/libkrb5support.so.0.1
7f492748f000-7f4927490000 rw-p 0000e000 fd:00 5512479                    /usr/lib64/libkrb5support.so.0.1
7f4927490000-7f49274a5000 r-xp 00000000 fd:00 5505788                    /usr/lib64/libz.so.1.2.7Aborted```

**Comment by vague666** [comment]
It's a known bug, https://github.com/irssi/irssi/pull/920/files#diff-a3c01d821a2da555ecb069eb457016f1R1195

**Comment by kli0rf** [comment]
@vague666 I see. Is there any fix for that?

**Comment by vague666** [comment]
No. What exactly are you trying to do?

**Comment by kli0rf** [comment]
As i described above: to unload the trigger.pl with the trigger. It worked before and now it doesn't.

**Comment by vague666** [comment]
Why are you trying to unload the script?

**Comment by kli0rf** [comment]
Why comment on something if you ain't got anything useful to say? Yes, i have to stick to my lame workaround, and no, rolling back perl is not an option. I don't see why would you need to understand my reasons of doing this or that, a simple "no, there's no fix for that, and there's not going to be" would suffice. Anyway, thanks for your replies.

**Comment by vague666** [comment]
Because if you told us the reason we might be able to help you with a better solution, but never mind, have fun!

**Comment by kli0rf** [comment]
The only help i need is fixing this bug. That's it. :)
