### ISSUE TITLE
colorize_nicks.pl error

### ISSUE THREAD

**Issue by PsySc0rpi0n** [irssi/scripts.irssi.org#552]
Hello.
I have just tried to load this script after downloading it to irssi/scripts and symlinking it in irssi/scirpts/autorun and I get the following error:

01:12 -!- Irssi: Error in script colorize_nicks:
01:12 Excessively long <> operator at /home/<user>/.irssi/scripts/colorize_nicks.pl line 21.

I'm using irssi irssi 1.0.7-1~deb9u1 (20180213 0139) in Debian 8.5

**Comment by vague666** [comment]
Download the script again and make sure you don't get the html page of it :)

**Comment by PsySc0rpi0n** [comment]
@vague666 you should play the lottery or jackpot or whatever! :p Thanks Can be closed!
