### ISSUE TITLE
[elist.pl] List command refuses to run without -YES option

### ISSUE THREAD

**Issue by jonpavelich** [irssi/scripts.irssi.org#630]
The `/LIST` command requires the `-YES` option to confirm the user wants a large amount of data to be sent to the client. Currently, `elist.pl` does not include this option, so attempting to use it prints a warning message and does not list any channels.

Running `/elist min=1000` on Freenode gives:
```
[Freenode] <--> elist (min=500, max=10000, mask='')
-!- Irssi: Doing this is not a good idea. Add -YES option to command if you really mean it
```

I was unable to find any way to disable this warning in the Irssi docs, please let me know if I am missing something. I've confirmed changing `$server->command("LIST " ...);` to `$server->command("LIST -YES " ...);` on line 81 resolves this issue. If this is an acceptable solution, I would be happy to submit a pull request for this.

**Comment by bw1** [comment]
hm

### standart
[rfc1459](https://tools.ietf.org/html/rfc1459)
```
4.2.6 List message

      Command: LIST
   Parameters: [<channel>{,<channel>} [<server>]]

   The list message is used to list channels and their topics.  If  the
   <channel>  parameter  is  used,  only  the  status  of  that  channel
   is displayed.  Private  channels  are  listed  (without  their
   topics)  as channel "Prv" unless the client generating the query is
   actually on that channel.  Likewise, secret channels are not listed
```

### freenode
see /msg alis help list


###  web search
 * [netsplit](http://irc.netsplit.de/channels/)
  * [kiwiirc](https://kiwiirc.com/search)
  * ...

**Comment by ailin-nemui** [comment]
maybe the pull request / code should check , that either the command is

/elist -yes

before adding -yes to /list (there is legitimate concerns on some servers that the list output is too large)

by the way, there is also /list >500 (without elist script)

**Comment by jonpavelich** [comment]
I didn't realize that `-yes` was a non-standard Freenode modification, thanks for the information @bw1. After more consideration, I agree with @ailin-nemui that adding `-yes` as an optional argument to the `elist` command could be a good solution - the default behaviour wouldn't change in any way, and on servers that prompt for `-yes` the user can simply add it to the `elist` command to have it passed through. This preserves the warning in the case that `/list` would return too much data, but the confusing behaviour of being prompted for `-yes` but adding it having no effect would be fixed. 

Is this a more acceptable solution? If so I'll start on a pull request.

(Also I had no idea `/list` supported a minimum users argument like that, thanks for the info!)

**Comment by ailin-nemui** [comment]
just for clarification, -yes is some protection / modification done by Irssi, not freenode :-)

**Comment by jonpavelich** [comment]
Ah okay, makes sense. I'll submit a pull request later today with the described changes.

**Comment by jonpavelich** [comment]
Pull request is up. I didn't modify the usage comment because `-YES` is a somewhat confusing option when not required, and Irssi nicely prompts the user for it when it is actually required. Also my Perl is pretty shaky, so please let me know if there's anything I could have done in a better way.
