### ISSUE TITLE
nickcolor_expando uses one colour even defined for more

### ISSUE THREAD

**Issue by hrw** [irssi/scripts.irssi.org#681]
Terminal has colours, /cubes and /neatcolor shows them. But nickcolor_expando.pl (0.4.0 latest version) displays all nicks in same colour:

![obraz](https://user-images.githubusercontent.com/185508/69581274-85c63980-0fd6-11ea-8dbc-c9fbc4261ab2.png)

What's wrong? nickcolor.pl randomized colours for nicks but had far too small amount of them to use.

**Comment by ailin-nemui** [comment]
did you maybe forget to set it up properly?

https://github.com/irssi/scripts.irssi.org/blob/6fbbf2b8accb352c7703fedda329ba016eb37687/scripts/nickcolor_expando.pl#L19

**Comment by hrw** [comment]
oops.
