### ISSUE TITLE
[nickcolor_expando.pl] Script doesn't work automatically

### ISSUE THREAD

**Issue by AE** [irssi/scripts.irssi.org#690]
It looks like at the moment, I have to run 
 /format pubmsg {pubmsgnick $2 {pubnick $nickcolor$0}}$1
every time I restart irssi. I tried to add it to autorun or as part of the autosendcmd but these seem to be messing everything up. I can't set this to run at startup. I tried using it in conjunction with nm2 but I don't like the way that script makes changes to how it writes usernames.

**Comment by vague666** [comment]
If you have the latest versions of both nickcolor_expando and nm2 they will work fine together. nm2 will take advantage of nickcolor_expando
Make sure you /save after doing the format change so that the changes are written to disk

**Comment by AE** [comment]
Thanks, I didn't want to run it with nm2 due to the way nm2 modifies how nicks are displayed I needed to run /save which I didn't know and couldn't find any documentation about anywhere. Running /save after the /format command as specified in the script works. Cheers and thanks for the effort the community is putting into this :)
