### ISSUE TITLE
[colorize_nicks?] Improve regexp

### ISSUE THREAD

**Issue by incognico** [irssi/scripts.irssi.org#694]
I think colorize_nicks.pl (not 100% sure if nickcolor_expando.pl inteacts with it) could be improved a little. It hilights nicknames in written lines.

Currently it has problems with umlauts, öäüß, treating them as separator chars.

The nickname H exists in the channel:
![image](https://user-images.githubusercontent.com/2098066/77252696-e6e4dd80-6c55-11ea-81e6-cf16eb810ac8.png)

With `hello` it would not have hilighted the nickname.

**Comment by ailin-nemui** [comment]
I improved this in colorize_nicks 0.4.0

**Comment by incognico** [comment]
Thanks, works fine now!
