### ISSUE TITLE
[server_time.pl] Doesn't display correct timestamps with ZNC

### ISSUE THREAD

**Issue by xbeyond1** [irssi/scripts.irssi.org#699]
When I'm connecting to my ZNC, the timestamps show the time when I connected to the server rather than when the messages were actually sent. 

OS: Linux Mint 19.3 Cinnamon
Client: Irssi 1.0.5

[edit]

I reinstalled irssi and noticed that the problem starts only when I want to display seconds in my timestamp as well (using the /FORMAT timestamp {timestamp %%H:%%M:%%S} command). When just displaying hours and minutes, the script works fine.

**Comment by ailin-nemui** [comment]
you cn try irssi/irssi#1108

**Comment by xbeyond1** [comment]
> you can try [irssi/irssi#1108](https://github.com/irssi/irssi/pull/1108)

You mean install the latest version of irssi? How can I do that on Linux Mint? The apt repository only has 1.0.5.

**Comment by ailin-nemui** [comment]
ah, if you have never installed software manually it may be a bit challenging. If you still want to try here are some short terminal command line instructions:
```
git clone https://github.com/irssi/irssi irssi-source
cd irssi-source
curl -LO https://github.com/irssi/irssi/pull/1108.patch
git am 1108.patch
sudo apt install libperl-dev libglib2.0-dev build-essential meson
meson Build
ninja -C Build && sudo ninja -C Build install
```

**Comment by xbeyond1** [comment]
> ah, if you have never installed software manually it may be a bit challenging. If you still want to try here are some short terminal command line instructions:
> 
> ```
> git clone https://github.com/irssi/irssi irssi-source
> cd irssi-source
> curl -LO https://github.com/irssi/irssi/pull/1108.patch
> git am 1108.patch
> sudo apt install libperl-dev libglib2.0-dev build-essential meson
> meson Build
> ninja -C Build && sudo ninja -C Build install
> ```

I gave it a shot and when I entered "meson Build", I got the following error:

meson.build:325:30: ERROR: Expecting eol got id.
      if get_option('prefix') in ['/usr/local', 'C:/']

**Comment by ailin-nemui** [comment]
ah, that means the meson program included with your Linux Mint version is very old :( (Issue https://github.com/irssi/irssi/issues/1066). However if you don't want to give up yet, you can do:
```
sudo apt purge meson
```
to remove the old meson and try if you can run
```
pip3 install meson
```
to install the new version of meson from the python repositories

**Comment by xbeyond1** [comment]
> ah, that means the meson program included with your Linux Mint version is very old :( (Issue [irssi/irssi#1066](https://github.com/irssi/irssi/issues/1066)). However if you don't want to give up yet, you can do:
> 
> ```
> sudo apt purge meson
> ```
> 
> to remove the old meson and try if you can run
> 
> ```
> pip3 install meson
> ```
> 
> to install the new version of meson from the python repositories

Thanks for being patient! Yes, I'll definitely want to get to the bottom of this. So when I tried to install meson using pip3, I got the following error:

>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kjveynxl/meson/

**Comment by ailin-nemui** [comment]
hard to tell, the error is not very informative. try running pip3 with sudo?

**Comment by xbeyond1** [comment]
> hard to tell, the error is not very informative. try running pip3 with sudo?

Apparently, the setup-tools for pip were missing, I managed to reinstall them. When I entered "meson Build", I got the message that some libraries are missing (see pic) -- is there a way to install them all?

**Comment by ailin-nemui** [comment]
now

**Comment by ailin-nemui** [comment]
try installing libtinfo-dev or libncurses-dev with apt

**Comment by xbeyond1** [comment]
> try installing libtinfo-dev or libncurses-dev with apt

This worked - thank you!

Also, irssi 1.3 installed successfully, I turned on server time, connected to my ZNC, and the logs were displayed perfectly. Thanks!

**Comment by xbeyond1** [comment]
> you can try [irssi/irssi#1108](https://github.com/irssi/irssi/pull/1108)

Is there a way to get scriptassist working with that version?

**Comment by ailin-nemui** [comment]
/load perl
/run scriptassist

to make it automatic, create a file `~/.irssi/startup`  with the following content:
```
load perl
```
