### ISSUE TITLE
Some scripts/updates I'd like to see

### ISSUE THREAD

**Issue by incognico** [irssi/scripts.irssi.org#7]
I'm not merging them in by myself, I'll rather mention the authors so they can add their scripts themselves. Maybe they want to add some more scripts too :)

Missing scripts in this repository:
- [x] https://github.com/rcaputo/irssi-ack/blob/master/ack.pl @rcaputo 
- [x] https://github.com/grawity/code/blob/master/irssi/auth_quakenet.pl @grawity 
- [x] http://tomaw.net/irssi/banaffects.pl @tomaw 
- [x] https://github.com/atheme/atheme/blob/master/contrib/cap_sasl.pl @atheme
- [x] https://github.com/shabble/irssi-scripts/blob/master/colour-popup/colour_popup.pl @shabble
- [x] hlscroll.pl @Juerd
- [x] https://github.com/phyber/irssi-scripts/blob/master/quakequit.pl @phyber
- [x] http://explodingferret.com/linux/irssi/query_whois.pl @ferret

Scripts with newer versions available:
- [x] https://github.com/phyber/irssi-scripts/blob/master/bantime.pl (1.03->0.5) @phyber
- [x] https://dgl.cx/irssi/title.pl (3.2b->3.2) @dgl

**Comment by ailin-nemui** [comment]
@GeertHauwaerts  any progress there?

**Comment by brabo** [comment]
I've been happy using https://github.com/mquin/irssi-scripts/blob/master/cap-extjoin.pl for quite some years now. considering ircv3 is getting more a thing, it would be nice to see it added.
@mquin?

**Comment by bw1** [comment]
<https://dgl.cx/irssi/title.pl>  is already fixed [#10]
@ailin-nemui

**Comment by bw1** [comment]
[check-irssi-scripts](https://github.com/bw1/check-irssi-scripts)
[![Build Status](https://travis-ci.org/bw1/check-irssi-scripts.svg?branch=master)](https://travis-ci.org/bw1/check-irssi-scripts)

### can be closed

**Comment by ailin-nemui** [comment]
nice
