### ISSUE TITLE
[scriptassist.pl] the version 2020042700 does not start

### ISSUE THREAD

**Issue by g4570n** [irssi/scripts.irssi.org#705]
I am using `irssi-git` version `1.3dev-273-g86b72d58`, since I updated `scriptassist.pl` to the latest version (`2020042700`), when I try to load the script, I get this error:

```
/script load scriptassist.pl
Irssi: Error in script scriptassist:
Irssi: Invalid version format (non-numeric data) at 
          /usr/share/perl/5.28/version.pm line 59.
```

**Comment by ailin-nemui** [comment]
please try updating your irssi package to irssi-git_1.3dev+273+g86b72d58-458.1 see if that helps

**Comment by g4570n** [comment]
Yes, I upgraded to that version and the problem was solved. Thank you :)
