### ISSUE TITLE
[trackbar.pl] error: Modification of non-creatable hash value attempted

### ISSUE THREAD

**Issue by nikola-benes** [irssi/scripts.irssi.org#706]
Whenever I join a new channel (or otherwise create a new irssi window), the trackbar script fails with the following error:

```
-!- Irssi: Error in script trackbar:
Modification of non-creatable hash value attempted, subscript "cur_line" at $HOME/.irssi/scripts/trackbar.pl line 303.
```

I use the default trackbar settings.

**Comment by vague666** [comment]
Do you have the latest version?

**Comment by ailin-nemui** [comment]
I can see this issue should be fixed in trackbar (line 303 tries to create cur_line) but on the other hand normally trackbar does not draw a trackbar on empty windows. So I wonder how this issue happens to you

**Comment by ailin-nemui** [comment]
you can also test if this fixes it for you @nikola-benes but it would still be interesting to know how you ran into the issue exactly (I do not get it on a fresh Irssi unless I run /mark on the empty window)

**Comment by nikola-benes** [comment]
I have configured my return key to run `/mark` after sending the line, that might be the cause of the problem. #707 seems to fix the problem, thank you.
