### ISSUE TITLE
Excessively long <> operator at ... line 20

### ISSUE THREAD

**Issue by andreasmjg** [irssi/scripts.irssi.org#719]
Hi, I tried to download the following two scripts to my .irssi/scripts folder: 

https://github.com/irssi/scripts.irssi.org/blob/master/scripts/hilightwin.pl
https://github.com/irssi/scripts.irssi.org/blob/master/scripts/trackbar.pl

and tried running /script load scriptname for both.

I get back: 

```
10:01 -!- Irssi: Error in script trackbar:
10:01 Excessively long <> operator at /home/user/.irssi/scripts/trackbar.pl line 20.
```

and 

```
10:03 -!- Irssi: Error in script hilightwin:
10:03 Excessively long <> operator at /home/user/.irssi/scripts/hilightwin.pl line 20.
```

I could load smartfilter.pl just fine..

Any help appreciated.

Thank you! 
Andreas

**Comment by dwfreed** [comment]
Could you verify those files have perl in them and not HTML? If you directly downloaded the URLs you gave, you probably got HTML (which is where using scriptassist to install scripts is helpful, because it would correctly download the raw perl files, not the GitHub pages).

**Comment by ailin-nemui** [comment]
I guess you did *not* use scriptassist?

**Comment by andreasmjg** [comment]
I did use scriptassist but I didn't download the raw file but the html page and put that in the scripts folder.

/facepalm

Downloaded the raw scripts and it works now - thank you
