### ISSUE TITLE
Irssi: Unknown setting awl_display_key

### ISSUE THREAD

**Issue by cameronhopkin** [irssi/scripts.irssi.org#736]
Hello Just getting back into IRSSI and am running new Mac OS 11 - had issues with trust for certificate authority that I fixed through there issue section. Now I am getting an unknown setting error for awl_display_key.  I checked for awl_display_key in the adv_windowlist.pl script and didn't see it. I checked for any issues listed in the repo and also didn't see anything there.

I am using Iterm 2 - Irssi was installed with Home brew. 
Mac OS 11.0.4
Iterm Build 3.4.1
irssi 1.2.2 (20190829 0225)
Oh-my-zsh

Run Irssi and then /run scriptassist with no errors

I have tried to reload the scripts 

File Directory:
➜  scripts ls -ll
total 240
-rw-r--r--  1 hopkinct  staff  90252 Nov 21 11:13 adv_windowlist.pl
drwxr-xr-x  5 hopkinct  staff    160 Nov 21 11:18 autorun
-rw-r--r--  1 hopkinct  staff   2610 Nov 21 11:15 hilightwin.pl
-rw-r--r--  1 hopkinct  staff  24149 Nov 21 11:14 nicklist.pl
drwxr-xr-x  2 hopkinct  staff     64 Nov 21 11:13 old
➜  scripts ls -ll ./autorun
total 0
lrwxr-xr-x  1 hopkinct  staff  48 Nov 21 11:17 adv_windowlist.pl -> /Users/hopkinct/.irssi/scripts/adv_windowlist.pl
lrwxr-xr-x  1 hopkinct  staff  44 Nov 21 11:18 hilightwin.pl -> /Users/hopkinct/.irssi/scripts/hilightwin.pl
lrwxr-xr-x  1 hopkinct  staff  42 Nov 21 11:18 nicklist.pl -> /Users/hopkinct/.irssi/scripts/nicklist.pl

**Comment by ailin-nemui** [comment]
don't follow outdated random guides on the internet, try /format awl_display_key

see the manual: https://github.com/irssi/scripts.irssi.org/blob/master/scripts/adv_windowlist.pl#L47

**Comment by cameronhopkin** [comment]
Thanks for pointing to the update from /set to /format - There really aren't any up-to-date guides out there guess I should rectify that.
