### ISSUE TITLE
[il.pl] doesn't populate line count

### ISSUE THREAD

**Issue by bruceleerabbit** [irssi/scripts.irssi.org#745]
First problem: The usage is undocumented.  

2nd problem: In IRSSI 1.2.2 the command `/statusbar window add inputlength` is accepted (after first doing `/run il.pl`) but it only expands the statusbar by an extra line.  The count never appears.

**Comment by bw1** [comment]
/help statusbar
```
STATUSBAR ADDITEM|MODIFYITEM [-before | -after <item>] [-priority #] [-alignment left|right] <item> <statusbar>
STATUSBAR REMOVEITEM <item> <statusbar>
```

/statusbar info window
```
21:14 Statusbar: window
21:14 Type     : window
21:14 Placement: bottom
21:14 Position : 1
21:14 Visible  : active
21:14 Items    : Name                                Priority  Alignment
21:14          : barstart                            100       left
21:14          : time                                0         left
21:14          : user                                0         left
21:14          : window                              0         left
21:14          : window_empty                        0         left
21:14          : lag                                 -1        left
21:14          : act                                 10        left
21:14          : more                                -1        right
21:14          : barend                              100       right
21:14          : boinc_credit                        0         left
21:14          : inputlength                         0         left
```

![bild](https://0x0.st/-zPd.svg)

please test:
```
/run il.pl
/STATUSBAR ADDITEM inputlength window
```

**Comment by bruceleerabbit** [comment]
```
-!- Irssi: Loaded script il
-!- Irssi: Unknown statusbar command: inputlength
```

**Comment by ailin-nemui** [comment]
then you are not using Irssi 1.2

**Comment by bw1** [comment]
![irssi v1.0.7](https://0x0.st/-zZv.png)

**Comment by bruceleerabbit** [comment]
ah, i have Irssi v1.0.7-1~deb9u1 also.. not sure why i thought 1.2.2 earlier.  And it works.  After restarting I discovered the count was running off the screen because it's to the right of the 50+ windows that I have.

Thanks for the help folks!  Sorry it turned into an SUE (stupid user error).  I'll leave the ticket open though, because I still think there is a documentation bug here (lack of docs).  The doc should start off with the usage syntax (most importantly mention the \statusbar command), and push the programming esoterics below that.  I also suggest that the docs suggest using the `-after user` option to ensure the count doesn't run off.
