### ISSUE TITLE
Installed some autojoin plugins, auto part reclaim, change username when logged back in, they dont work or need instructions in readme.md

### ISSUE THREAD

**Issue by kangarooo** [irssi/scripts.irssi.org#833]
Theese installed, somehow found i can add them to autostart- but they dont do anything to rejoin or reclaim nick when parting in other client and dont join servers and save channels and dont auto ident.
06:15 ,--[ScriptAssist
06:15 | o UNIBG-autoident        Up to date. (0.2)
06:15 | o auto_whois             Up to date. (0.9)
06:15 | o autostuff              Up to date. (0.02)
06:15 | o autowho                Up to date. (0.1)
06:15 | o ident                  Up to date. (1.0)
06:15 | o mouse                  Up to date. (1.1.2)
06:15 | o scriptassist           Up to date. (2022053100)
06:15 | o tmux-nicklist-portable Up to date. (0.1.8)

**Comment by bw1** [comment]
* UNIBG-autoident
  +  Automaticaly /msg ident NS yourpassword Automaticaly /msg ident NS yourpassword when you
* auto_whois
  + /WHOIS all the users who send you a private message.
* autostuff
  + Save current servers, channels and windows for autoconnect and autojoin
* autowho
  + Periodically sends /who on configured channels to update away state.
* ident
  + Automatically IDENTIFY when prompted
* mouse
  + control irssi using mouse clicks and gestures
* scriptassist
  + keeps your scripts on the cutting edge
* tmux-nicklist-portable
  + displays a list of nicks in a separate tmux pane

**Comment by bw1** [comment]
* network?
* server?
* https://netsplit.de/networks/statistics.php?net=UniBG
* https://github.com/irssi/scripts.irssi.org/blob/master/scripts/autostuff.pl
* https://github.com/irssi/scripts.irssi.org/blob/master/scripts/ident.pl

**Comment by kangarooo** [comment]
irc.oftc.net
irc.libera.chat
i did /connect /msg nickserv identify /j #some 
i did command /save
/quit
opening nothing happens
maybe one interferring in other?
Maybe need more plugins to auto rename when other client quits and auto rename when main nick identifies and new app?

**Comment by bw1** [comment]
* oftc <https://www.oftc.net/NickServ/CertFP/#automatically-identifying-using-ssl--certfp>
* libera <https://libera.chat/guides/irssi>
* <https://irssi.org/documentation/help/connect/>
*  more scripts -> <https://scripts.irssi.org/>
* no need for plugin to identify the client
