### ISSUE TITLE
needs a disclaimer

### ISSUE THREAD

**Issue by ghost** [irssi/scripts.irssi.org#86]
I'm finding a lot of these scripts don't even work. If you: 

- enable all of the scripts in autorun/ 
- scandeps.pl *.pl > ~/.irssi/module_deps
- while read in; do cpan i $(echo $in | awk '{ print $1 }' | sed "s/'//g" ); done < module_deps 

Alot of dependencies aren't even available in cpan. A ton of the scripts still won't work. Also, what's to say there aren't backdoors in any of these scripts?

**Comment by ailin-nemui** [comment]
a lot of scripts are outdated or of bad quality. they are just an import of the legacy collection. more thorough checking also for security issues would surely be beneficial but I think irssi.org doesn't have the manpower

**Comment by ailin-nemui** [comment]
@ahf user has deleted himself, close?

**Comment by GeertHauwaerts** [comment]
The script archive will be thoroughly revised in the future; I am closing this for now.
