### ISSUE TITLE
discord_unbridge.pl creating errant space after first letter of username?

### ISSUE THREAD

**Issue by bixfrankonis** [irssi/scripts.irssi.org#872]
I haven't been on IRC in ages, but I just logged into the server where I'd been using this script and it's still working fine *except* for the fact that the usernames coming through look like

`<u sername>`

instead of

`<username>`

and I'm entirely ignorant of what could be causing this?

**Comment by bw1** [comment]
@snan

**Comment by snan** [comment]
Maybe something changed on Discord?😵‍💫
