### ISSUE TITLE
Enable Travis CI for Scripts

### ISSUE THREAD

**Issue by ahf** [irssi/scripts.irssi.org#9]
It would be nice if someone could look into getting Travis CI running for irssi/scripts.git with the following features:

- For every pull-request, run some Perl analyzer that can emit warnings and errors, for all new and modified *.pl files in the changeset.
- Return an error on warning/error such that we can quickly spot problems with the scripts.

I don't have the needed Perl knowledge to do this, so I will let it be up for someone else to take care of.

**Comment by ailin-nemui** [comment]
@ahf close?

**Comment by GeertHauwaerts** [comment]
See #14 for more information.
