### ISSUE TITLE
nickcolor.pl with 256 colors please?

### ISSUE THREAD

**Issue by kaihendry** [irssi/scripts.irssi.org#90]
Not sure how to get this going. IIUC https://raw.githubusercontent.com/irssi/scripts.irssi.org/gh-pages/scripts/nickcolor.pl suggests we should just use ~13 colours and then I'm suffering with conflicts, i.e. nicks with same colours.

**Comment by ysangkok** [comment]
Check out https://github.com/shabble/irssi-docs/wiki/Irssi-0.8.17#Nick_colouring_script_for_256_colours
